services:
  mysql:
    image: mysql:8.4.8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: course
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
volumes:
  mysql-data:
