services:
  mysql:
    image: mysql:8.4.8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: course
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    tmpfs:
      - /data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:3.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.5.0
    volumes:
      - ./infra/promtail/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/logs
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
