spring:
  datasource:
    url: jdbc:tc:mysql:8.4.8://localhost:3306/course?useSSL=false&serverTimezone=UTC&TC_DAEMON=true&user=root&password=password&useInformationSchema=true
    username: root
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
auth:
  token:
    access-expires-in: 3600 # 1 hour
    refresh-expires-in: 86400 # 24 hours
    salt: "saltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsaltsalt"
